spring:
  application:
    name: cioc-sync-service1
  data:
    mongodb:
      host: 10.0.2.10
      port: 27017
      database: elia
      username: cioc-elia
      password: aBcD1234eF5678gH

logging:
  file:
    path: ./log
  level:
    root: INFO
    com:
      cioc: DEBUG

e2x:
  config:
    sync:
      taskGroup: 3
      sync_interval_seconds: 120
      sync_da_price_enable: true
    api_address: http://127.0.0.1:8088
